In [1]:
import pandas as pd
import numpy as np
from src import scout_car_clean as scc

%load_ext autoreload
%autoreload 2

In [2]:
import os
print(os.getcwd())

/media/oem/onetbsamdot/ezt/github/magnimind_hw


In [3]:
df_org = pd.read_json('./data/scout_car.json', lines=True)
df = df_org.copy()

In [4]:
"""
**Columns**
* url: url of autos
* short_description, description: Description of autos (in English and German) written by users
* make_model, make, model: Model of autos. Ex:Audi A1
* body_type, body: Body type of autos Example: van, sedans
* vat: VAT deductible, price negotiable
* registration, first_registration: First registration date and year of autos.
* prev_owner, previous_owners: Number of previous owners
* type: new or used
* next_inspection, inspection_new: information about inspection (inspection date,..)
* body_color, body_color_original: Color of auto Ex: Black, red
* paint_type: Paint type of auto Ex: Metallic, Uni/basic
* upholstery: Upholstery information (texture, color)
* gearing_type: Type of gear Ex: automatic, manual
* fuel : fuel type Ex: diesel, benzine
* co2_emission, emission_class, emission_label: emission information
* drive_chain: drive chain Ex: front,rear, 4WD
* consumption: consumption of auto in city, country and combination (lt/100 km)
* country_version
* entertainment_media
* safety_security
* comfort_convenience
* extras
* price: Price of cars
* km: km of autos
* hp: horsepower of autos (kW)
* displacement: displacement of autos (cc)
* warranty: warranty period (month)
* weight: weight of auto (kg)
* nr_of_doors: number of doors
* nr_of_seats : number of seats
* cylinders: number of cylinders
* gears: number of gears

"""

'\n**Columns**\n* url: url of autos\n* short_description, description: Description of autos (in English and German) written by users\n* make_model, make, model: Model of autos. Ex:Audi A1\n* body_type, body: Body type of autos Example: van, sedans\n* vat: VAT deductible, price negotiable\n* registration, first_registration: First registration date and year of autos.\n* prev_owner, previous_owners: Number of previous owners\n* type: new or used\n* next_inspection, inspection_new: information about inspection (inspection date,..)\n* body_color, body_color_original: Color of auto Ex: Black, red\n* paint_type: Paint type of auto Ex: Metallic, Uni/basic\n* upholstery: Upholstery information (texture, color)\n* gearing_type: Type of gear Ex: automatic, manual\n* fuel : fuel type Ex: diesel, benzine\n* co2_emission, emission_class, emission_label: emission information\n* drive_chain: drive chain Ex: front,rear, 4WD\n* consumption: consumption of auto in city, country and combination (lt/100 k

In [5]:
# Replace special characters and spaces in column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[\s\n]+', '_', regex=True)
    .str.replace(r'[^a-z0-9_]', '', regex=True)
    .str.replace(r'_+', '_', regex=True)
)

df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kw', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'nonsmoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'description',
       'emission_label', 'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [6]:
df.drop(['entertainment_media', 'safety_security', 'comfort_convenience', 'extras'],axis=1,inplace=True)
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kw', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'nonsmoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co2_emission', 'emission_class', 'description', 'emission_label',
       'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [7]:
len(np.unique(df['url']))

15919

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   url                            15919 non-null  object 
 1   make_model                     15919 non-null  object 
 2   short_description              15873 non-null  object 
 3   body_type                      15859 non-null  object 
 4   price                          15919 non-null  int64  
 5   vat                            11406 non-null  object 
 6   km                             15919 non-null  object 
 7   registration                   15919 non-null  object 
 8   prev_owner                     9091 non-null   object 
 9   kw                             0 non-null      float64
 10  hp                             15919 non-null  object 
 11  type                           15917 non-null  object 
 12  previous_owners                9279 non-null  

In [9]:
df.shape

(15919, 50)

In [10]:
# url unique count
len(np.unique(df['url']))

15919

In [11]:
# make_model unique count
len(np.unique(df['make_model']))

9

In [12]:
np.unique(df['make_model'], return_counts=True,equal_nan=True)

(array(['Audi A1', 'Audi A2', 'Audi A3', 'Opel Astra', 'Opel Corsa',
        'Opel Insignia', 'Renault Clio', 'Renault Duster',
        'Renault Espace'], dtype=object),
 array([2614,    1, 3097, 2526, 2219, 2598, 1839,   34,  991]))

In [13]:
df['make_model'] = df['make_model'].str.lower().str.replace(' ', '_')
np.unique(df['make_model'], return_counts=True,equal_nan=True)

(array(['audi_a1', 'audi_a2', 'audi_a3', 'opel_astra', 'opel_corsa',
        'opel_insignia', 'renault_clio', 'renault_duster',
        'renault_espace'], dtype=object),
 array([2614,    1, 3097, 2526, 2219, 2598, 1839,   34,  991]))

In [14]:
# short description unique count
df['short_description'].fillna('none', inplace=True)
np.unique(df['short_description'], return_counts=True,equal_nan=True)

(array([' 1,6 CDTI**NAVI*Klimaaut*Tempomat*EURO6*TÜV NEU',
        ' 1.4 75 cv5 porte b-color', ' 1.4 TFSI Attraction (125 CV)', ...,
        'van 1.5 dci 75cv S&S E6', 'zoé life', 'Österr. Edition 16.CDTI'],
       dtype=object),
 array([ 1,  1,  6, ..., 24,  1,  1]))

In [15]:
df['short_description'].isnull().sum()

0

In [16]:
df['short_description'].fillna('none', inplace=True)
df['short_description'].isnull().sum()

0

In [17]:
# body type
df['body_type'].fillna('none', inplace=True)
df['body_type'] = df['body_type'].str.lower().str.replace('-', '_').str.replace(' ', '_')
np.unique(df['body_type'], return_counts=True,equal_nan=True)

(array(['compact', 'convertible', 'coupe', 'none', 'off_road', 'other',
        'sedans', 'station_wagon', 'transporter', 'van'], dtype=object),
 array([3153,    8,   25,   60,   56,  290, 7903, 3553,   88,  783]))

In [18]:
# price null check
df['price'].isnull().sum()

0

In [19]:
# vat
df['vat'].fillna('none', inplace=True)
df['vat'] = df['vat'].str.lower().str.replace(' ', '_')
np.unique(df['vat'], return_counts=True,equal_nan=True)

(array(['none', 'price_negotiable', 'vat_deductible'], dtype=object),
 array([ 4513,   426, 10980]))

In [20]:
df['vat'].isnull().sum()

0

In [21]:
# km null check
df['km'].isnull().sum()

0

In [22]:
# registration null check:
df['registration'].isnull().sum()

0

In [23]:
np.unique(df['registration'], return_counts=True,equal_nan=True)

(array(['-/-', '01/2016', '01/2017', '01/2018', '01/2019', '02/2016',
        '02/2017', '02/2018', '02/2019', '03/2016', '03/2017', '03/2018',
        '03/2019', '04/2016', '04/2017', '04/2018', '04/2019', '05/2016',
        '05/2017', '05/2018', '05/2019', '06/2016', '06/2017', '06/2018',
        '06/2019', '07/2016', '07/2017', '07/2018', '07/2019', '08/2016',
        '08/2017', '08/2018', '08/2019', '09/2016', '09/2017', '09/2018',
        '09/2019', '10/2016', '10/2017', '10/2018', '11/2016', '11/2017',
        '11/2018', '11/2019', '12/2016', '12/2017', '12/2018', '12/2019'],
       dtype=object),
 array([1597,  376,  306,  511,  541,  472,  368,  539,  585,  536,  471,
         695,  543,  532,  380,  541,  506,  459,  404,  572,  440,  452,
         409,  532,  224,  176,  215,  396,    6,   94,  114,  285,    1,
         141,  149,  141,    5,  160,  154,   97,  142,  180,  110,    1,
         134,  123,  103,    1]))

In [24]:
# Split the 'registration' column into 'registration_month' and 'registration_year'
df[['registration_month', 'registration_year']] = df['registration'].str.split('/', expand=True)

# Replace invalid entries with 'none'
df['registration_month'] = df['registration_month'].replace('-', 'none')
df['registration_year'] = df['registration_year'].replace('-', 'none')

# sample registration
df[['registration', 'registration_month', 'registration_year']].sample(25)

registration registration_month registration_year
14700          -/-               none              none
1405       03/2017                 03              2017
15005      08/2016                 08              2016
5573           -/-               none              none
5976       04/2017                 04              2017
11591      10/2017                 10              2017
10487      02/2016                 02              2016
11383      07/2017                 07              2017
8992       04/2016                 04              2016
12747      02/2019                 02              2019
930        03/2017                 03              2017
867        10/2017                 10              2017
11390      10/2017                 10              2017
1284       01/2017                 01              2017
13722      04/2016                 04              2016
7167       03/2018                 03              2018
10627      06/2016                 06              2016
3734       04/2018                 04              2018
3418       03/2016                 03              2016
32         03/2016                 03              2016
10115      01/2019                 01              2019
1814       06/2018                 06              2018
2250       02/2019                 02              2019
5352           -/-               none              none
12670      06/2019                 06              2019

In [25]:
# prev_owner
df['prev_owner'].fillna('none',inplace=True)
np.unique(df['prev_owner'], return_counts=True, equal_nan=True)

(array(['1 previous owner', '2 previous owners', '3 previous owners',
        '4 previous owners', 'none'], dtype=object),
 array([8294,  778,   17,    2, 6828]))

In [26]:
df['prev_owner'] = df['prev_owner'].str.replace(' ', '_')
np.unique(df['prev_owner'], return_counts=True, equal_nan=True)

(array(['1_previous_owner', '2_previous_owners', '3_previous_owners',
        '4_previous_owners', 'none'], dtype=object),
 array([8294,  778,   17,    2, 6828]))

In [27]:
# next inspection
df['next_inspection'].fillna('none',inplace=True)
df[df['next_inspection'] != 'none']['next_inspection'].sample(25)

9805                [\n11/2021\n, \n129 g CO2/km (comb)\n]
3463                 [\n09/2020\n, \n99 g CO2/km (comb)\n]
4819                [\n10/2021\n, \n121 g CO2/km (comb)\n]
7439                                           \n01/2021\n
8824                [\n03/2021\n, \n102 g CO2/km (comb)\n]
7203                [\n03/2021\n, \n121 g CO2/km (comb)\n]
7735                [\n01/2022\n, \n170 g CO2/km (comb)\n]
2162                [\n03/2020\n, \n110 g CO2/km (comb)\n]
11540                                          \n04/2020\n
1673                                           \n10/2022\n
7142     [\n06/2021\n, \n, 5.6 l/100 km (comb), \n, 7.3...
13061               [\n06/2019\n, \n120 g CO2/km (comb)\n]
14663               [\n01/2022\n, \n113 g CO2/km (comb)\n]
1547                          [\n03/2021\n, \n4 (Green)\n]
11994                         [\n06/2019\n, \n4 (Green)\n]
821                  [\n08/2020\n, \n94 g CO2/km (comb)\n]
15092                            [\n03/2021\n, \nEuro 6\

In [28]:
df['next_inspection'].iloc[10087]

['\n06/2021\n',
 '\n',
 '5.9 l/100 km (comb)',
 '\n',
 '7.5 l/100 km (city)',
 '\n',
 '5 l/100 km (country)',
 '\n']

In [29]:
df['inspection_new'].fillna('none',inplace=True)
df[df['inspection_new'] != 'none']['inspection_new'].sample(25)

590                      [\nYes\n, \n99 g CO2/km (comb)\n]
9314     [\nYes\n, \n, 5.9 l/100 km (comb), \n, 7.9 l/1...
6734                                             [\nYes\n]
263                     [\nYes\n, \n103 g CO2/km (comb)\n]
10391                   [\nYes\n, \n129 g CO2/km (comb)\n]
11732                   [\nYes\n, \n104 g CO2/km (comb)\n]
14372                   [\nYes\n, \n135 g CO2/km (comb)\n]
6314     [\nYes\n, \n, 5.6 l/100 km (comb), \n, 7.3 l/1...
5018                                 [\nYes\n, \nEuro 6\n]
13192                                [\nYes\n, \nEuro 6\n]
6413                     [\nYes\n, \n95 g CO2/km (comb)\n]
12216    [\nYes\n, \n, 6.1 l/100 km (comb), \n, 7.5 l/1...
3139                    [\nYes\n, \n101 g CO2/km (comb)\n]
6960                     [\nYes\n, \n95 g CO2/km (comb)\n]
3504                    [\nYes\n, \n105 g CO2/km (comb)\n]
8528                    [\nYes\n, \n142 g CO2/km (comb)\n]
806                     [\nYes\n, \n104 g CO2/km (comb)\

In [30]:
# hp
np.unique(df['hp'], return_counts=True, equal_nan=True)

(array(['- kW', '1 kW', '100 kW', '101 kW', '103 kW', '104 kW', '110 kW',
        '112 kW', '115 kW', '117 kW', '118 kW', '119 kW', '120 kW',
        '121 kW', '122 kW', '123 kW', '125 kW', '127 kW', '132 kW',
        '133 kW', '135 kW', '137 kW', '140 kW', '141 kW', '143 kW',
        '146 kW', '147 kW', '149 kW', '150 kW', '154 kW', '155 kW',
        '162 kW', '163 kW', '164 kW', '165 kW', '167 kW', '168 kW',
        '184 kW', '191 kW', '195 kW', '228 kW', '239 kW', '270 kW',
        '294 kW', '4 kW', '40 kW', '44 kW', '51 kW', '52 kW', '53 kW',
        '54 kW', '55 kW', '56 kW', '57 kW', '60 kW', '63 kW', '65 kW',
        '66 kW', '67 kW', '70 kW', '71 kW', '74 kW', '75 kW', '76 kW',
        '77 kW', '78 kW', '80 kW', '81 kW', '82 kW', '84 kW', '85 kW',
        '86 kW', '87 kW', '88 kW', '89 kW', '9 kW', '90 kW', '92 kW',
        '93 kW', '96 kW', '98 kW'], dtype=object),
 array([  88,   20, 1308,   47,  253,    8, 1112,    7,    1,    6,  516,
          30,    8,  392,   35,    1,  

In [31]:
df['kw'] = df['hp'].str.extract('(\d+)').copy()
df['kw'] = df['kw'].fillna('none').copy()
df['kw'].sample(4)

8394      66
15615    118
8262      66
12125    121
Name: kw, dtype: object

In [32]:
df['kw'].sample(4)

11976    100
11622    100
3668      81
6562      74
Name: kw, dtype: object

In [39]:
df[['kw','hp']].sample(50)

kw      hp
6706    110  110 kW
15562  none    - kW
12725   121  121 kW
8240     66   66 kW
13788   162  162 kW
12997   103  103 kW
5747    100  100 kW
15876   165  165 kW
12792    81   81 kW
6537    100  100 kW
12580   154  154 kW
1928    147  147 kW
11714   125  125 kW
3467     81   81 kW
13249    87   87 kW
8574     66   66 kW
5366     85   85 kW
7796    110  110 kW
11798   125  125 kW
3080     81   81 kW
3806     81   81 kW
13531    55   55 kW
5000     85   85 kW
15491   118  118 kW
14817    56   56 kW
2615    110  110 kW
9272     67   67 kW
2249     70   70 kW
13209    88   88 kW
8645     51   51 kW
9215     66   66 kW
10962   125  125 kW
7452     92   92 kW
6667    100  100 kW
5085     85   85 kW
10207    55   55 kW
15475   118  118 kW
7226    100  100 kW
10658   100  100 kW
15665   165  165 kW
4882     85   85 kW
9537     51   51 kW
11626   103  103 kW
7677    110  110 kW
12829   103  103 kW
15715   119  119 kW
1257     66   66 kW
4627     85   85 kW
15089   118  118 kW
8733     51   51 kW

In [40]:
!python3 scout_car_clean.py