In [1]:
import pandas as pd
import numpy as np
from src import scout_car_clean as scc

%load_ext autoreload
%autoreload 2

In [2]:
import os
print(os.getcwd())

/media/oem/onetbsamdot/ezt/github/magnimind_hw


In [3]:
df_org = pd.read_json('./data/scout_car.json', lines=True)
df = df_org.copy()

In [4]:
"""
**Columns**
* url: url of autos
* short_description, description: Description of autos (in English and German) written by users
* make_model, make, model: Model of autos. Ex:Audi A1
* body_type, body: Body type of autos Example: van, sedans
* vat: VAT deductible, price negotiable
* registration, first_registration: First registration date and year of autos.
* prev_owner, previous_owners: Number of previous owners
* type: new or used
* next_inspection, inspection_new: information about inspection (inspection date,..)
* body_color, body_color_original: Color of auto Ex: Black, red
* paint_type: Paint type of auto Ex: Metallic, Uni/basic
* upholstery: Upholstery information (texture, color)
* gearing_type: Type of gear Ex: automatic, manual
* fuel : fuel type Ex: diesel, benzine
* co2_emission, emission_class, emission_label: emission information
* drive_chain: drive chain Ex: front,rear, 4WD
* consumption: consumption of auto in city, country and combination (lt/100 km)
* country_version
* entertainment_media
* safety_security
* comfort_convenience
* extras
* price: Price of cars
* km: km of autos
* hp: horsepower of autos (kW)
* displacement: displacement of autos (cc)
* warranty: warranty period (month)
* weight: weight of auto (kg)
* nr_of_doors: number of doors
* nr_of_seats : number of seats
* cylinders: number of cylinders
* gears: number of gears

"""

'\n**Columns**\n* url: url of autos\n* short_description, description: Description of autos (in English and German) written by users\n* make_model, make, model: Model of autos. Ex:Audi A1\n* body_type, body: Body type of autos Example: van, sedans\n* vat: VAT deductible, price negotiable\n* registration, first_registration: First registration date and year of autos.\n* prev_owner, previous_owners: Number of previous owners\n* type: new or used\n* next_inspection, inspection_new: information about inspection (inspection date,..)\n* body_color, body_color_original: Color of auto Ex: Black, red\n* paint_type: Paint type of auto Ex: Metallic, Uni/basic\n* upholstery: Upholstery information (texture, color)\n* gearing_type: Type of gear Ex: automatic, manual\n* fuel : fuel type Ex: diesel, benzine\n* co2_emission, emission_class, emission_label: emission information\n* drive_chain: drive chain Ex: front,rear, 4WD\n* consumption: consumption of auto in city, country and combination (lt/100 k

In [5]:
# Replace special characters and spaces in column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[\s\n]+', '_', regex=True)
    .str.replace(r'[^a-z0-9_]', '', regex=True)
    .str.replace(r'_+', '_', regex=True)
)

df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kw', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'nonsmoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'description',
       'emission_label', 'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [6]:
df.drop(['entertainment_media', 'safety_security', 'comfort_convenience', 'extras', 'kw'],axis=1,inplace=True)
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kw', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'nonsmoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co2_emission', 'emission_class', 'description', 'emission_label',
       'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [7]:
len(np.unique(df['url']))

15919

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   url                            15919 non-null  object 
 1   make_model                     15919 non-null  object 
 2   short_description              15873 non-null  object 
 3   body_type                      15859 non-null  object 
 4   price                          15919 non-null  int64  
 5   vat                            11406 non-null  object 
 6   km                             15919 non-null  object 
 7   registration                   15919 non-null  object 
 8   prev_owner                     9091 non-null   object 
 9   kw                             0 non-null      float64
 10  hp                             15919 non-null  object 
 11  type                           15917 non-null  object 
 12  previous_owners                9279 non-null  

In [9]:
df.shape

(15919, 50)

In [10]:
# url unique count
len(np.unique(df['url']))

15919

In [11]:
# make_model unique count
len(np.unique(df['make_model']))

9

In [12]:
np.unique(df['make_model'], return_counts=True,equal_nan=True)

(array(['Audi A1', 'Audi A2', 'Audi A3', 'Opel Astra', 'Opel Corsa',
        'Opel Insignia', 'Renault Clio', 'Renault Duster',
        'Renault Espace'], dtype=object),
 array([2614,    1, 3097, 2526, 2219, 2598, 1839,   34,  991]))

In [13]:
df['make_model'] = df['make_model'].str.lower().str.replace(' ', '_')
np.unique(df['make_model'], return_counts=True,equal_nan=True)

(array(['audi_a1', 'audi_a2', 'audi_a3', 'opel_astra', 'opel_corsa',
        'opel_insignia', 'renault_clio', 'renault_duster',
        'renault_espace'], dtype=object),
 array([2614,    1, 3097, 2526, 2219, 2598, 1839,   34,  991]))

In [14]:
# short description unique count
df['short_description'].fillna('none', inplace=True)
np.unique(df['short_description'], return_counts=True,equal_nan=True)

(array([' 1,6 CDTI**NAVI*Klimaaut*Tempomat*EURO6*TÜV NEU',
        ' 1.4 75 cv5 porte b-color', ' 1.4 TFSI Attraction (125 CV)', ...,
        'van 1.5 dci 75cv S&S E6', 'zoé life', 'Österr. Edition 16.CDTI'],
       dtype=object),
 array([ 1,  1,  6, ..., 24,  1,  1]))

In [15]:
df['short_description'].isnull().sum()

0

In [16]:
df['short_description'].fillna('none', inplace=True)
df['short_description'].isnull().sum()

0

In [18]:
# body type
df['body_type'].fillna('none', inplace=True)
df['body_type'] = df['body_type'].str.lower().str.replace('-', '_').str.replace(' ', '_')
np.unique(df['body_type'], return_counts=True,equal_nan=True)

(array(['compact', 'convertible', 'coupe', 'none', 'off_road', 'other',
        'sedans', 'station_wagon', 'transporter', 'van'], dtype=object),
 array([3153,    8,   25,   60,   56,  290, 7903, 3553,   88,  783]))

In [19]:
# price null check
df['price'].isnull().sum()

0

In [21]:
# vat
df['vat'].fillna('none', inplace=True)
df['vat'] = df['vat'].str.lower().str.replace(' ', '_')
np.unique(df['vat'], return_counts=True,equal_nan=True)

(array(['none', 'price_negotiable', 'vat_deductible'], dtype=object),
 array([ 4513,   426, 10980]))

In [22]:
df['vat'].isnull().sum()

0

In [23]:
# km null check
df['km'].isnull().sum()

0

In [24]:
# registration null check:
df['registration'].isnull().sum()

0

In [25]:
np.unique(df['registration'], return_counts=True,equal_nan=True)

(array(['-/-', '01/2016', '01/2017', '01/2018', '01/2019', '02/2016',
        '02/2017', '02/2018', '02/2019', '03/2016', '03/2017', '03/2018',
        '03/2019', '04/2016', '04/2017', '04/2018', '04/2019', '05/2016',
        '05/2017', '05/2018', '05/2019', '06/2016', '06/2017', '06/2018',
        '06/2019', '07/2016', '07/2017', '07/2018', '07/2019', '08/2016',
        '08/2017', '08/2018', '08/2019', '09/2016', '09/2017', '09/2018',
        '09/2019', '10/2016', '10/2017', '10/2018', '11/2016', '11/2017',
        '11/2018', '11/2019', '12/2016', '12/2017', '12/2018', '12/2019'],
       dtype=object),
 array([1597,  376,  306,  511,  541,  472,  368,  539,  585,  536,  471,
         695,  543,  532,  380,  541,  506,  459,  404,  572,  440,  452,
         409,  532,  224,  176,  215,  396,    6,   94,  114,  285,    1,
         141,  149,  141,    5,  160,  154,   97,  142,  180,  110,    1,
         134,  123,  103,    1]))

In [26]:
# Split the 'registration' column into 'registration_month' and 'registration_year'
df[['registration_month', 'registration_year']] = df['registration'].str.split('/', expand=True)

# Replace invalid entries with 'none'
df['registration_month'] = df['registration_month'].replace('-', 'none')
df['registration_year'] = df['registration_year'].replace('-', 'none')

# sample registration
df[['registration', 'registration_month', 'registration_year']].sample(25)

registration registration_month registration_year
13836      02/2016                 02              2016
12464          -/-               none              none
13054          -/-               none              none
14848          -/-               none              none
6272       03/2017                 03              2017
8726       07/2016                 07              2016
6678       03/2018                 03              2018
10781      02/2017                 02              2017
8797       02/2016                 02              2016
11566      02/2018                 02              2018
6200       06/2016                 06              2016
15624      05/2018                 05              2018
11939      01/2018                 01              2018
13942      07/2017                 07              2017
666        03/2016                 03              2016
14005      03/2017                 03              2017
14817      03/2019                 03              2019
15478      02/2019                 02              2019
2765       10/2016                 10              2016
4717           -/-               none              none
12853      01/2019                 01              2019
6918       01/2017                 01              2017
5512           -/-               none              none
14935      12/2016                 12              2016
8669       06/2016                 06              2016

In [28]:
# prev_owner
df['prev_owner'].fillna('none',inplace=True)
np.unique(df['prev_owner'], return_counts=True, equal_nan=True)

(array(['1 previous owner', '2 previous owners', '3 previous owners',
        '4 previous owners', 'none'], dtype=object),
 array([8294,  778,   17,    2, 6828]))

In [29]:
df['prev_owner'] = df['prev_owner'].str.replace(' ', '_')
np.unique(df['prev_owner'], return_counts=True, equal_nan=True)

(array(['1_previous_owner', '2_previous_owners', '3_previous_owners',
        '4_previous_owners', 'none'], dtype=object),
 array([8294,  778,   17,    2, 6828]))

In [34]:
# next inspection
df['next_inspection'].fillna('none',inplace=True)
df[df['next_inspection'] != 'none']['next_inspection'].sample(25)

7864                [\n06/2020\n, \n134 g CO2/km (comb)\n]
10251               [\n06/2022\n, \n129 g CO2/km (comb)\n]
11427    [\n03/2021\n, \n, 6.7 l/100 km (comb), \n, 9.4...
5040                [\n03/2022\n, \n106 g CO2/km (comb)\n]
8450                             [\n08/2020\n, \nEuro 6\n]
15159               [\n06/2020\n, \n120 g CO2/km (comb)\n]
5807                [\n04/2021\n, \n122 g CO2/km (comb)\n]
10473               [\n12/2019\n, \n170 g CO2/km (comb)\n]
8570                [\n04/2020\n, \n137 g CO2/km (comb)\n]
1213                 [\n10/2020\n, \n97 g CO2/km (comb)\n]
2527                                           \n03/2022\n
14994               [\n05/2019\n, \n123 g CO2/km (comb)\n]
5364                [\n01/2022\n, \n117 g CO2/km (comb)\n]
10087    [\n06/2021\n, \n, 5.9 l/100 km (comb), \n, 7.5...
7494     [\n09/2019\n, \n, 4.7 l/100 km (comb), \n, 5.4...
4810                [\n07/2021\n, \n107 g CO2/km (comb)\n]
9316     [\n06/2019\n, \n, 4.7 l/100 km (comb), \n, 5.8.

In [39]:
df['next_inspection'].iloc[10087]

['\n06/2021\n',
 '\n',
 '5.9 l/100 km (comb)',
 '\n',
 '7.5 l/100 km (city)',
 '\n',
 '5 l/100 km (country)',
 '\n']

In [41]:
df['inspection_new'].fillna('none',inplace=True)
df[df['inspection_new'] != 'none']['inspection_new'].sample(25)

5020            [\nYes\n, \nEuro 6d-TEMP\n]
11434                 [\nYes\n, \nEuro 6\n]
8444     [\nYes\n, \n139 g CO2/km (comb)\n]
92                    [\nYes\n, \nEuro 6\n]
4994            [\nYes\n, \nEuro 6d-TEMP\n]
15520    [\nYes\n, \n135 g CO2/km (comb)\n]
9089                  [\nYes\n, \nEuro 6\n]
12071           [\nYes\n, \nEuro 6d-TEMP\n]
14342    [\nYes\n, \n113 g CO2/km (comb)\n]
11633    [\nYes\n, \n119 g CO2/km (comb)\n]
9359     [\nYes\n, \n150 g CO2/km (comb)\n]
13504                               \nYes\n
6760      [\nYes\n, \n92 g CO2/km (comb)\n]
3798                  [\nYes\n, \nEuro 6\n]
13688                               \nYes\n
8706     [\nYes\n, \n126 g CO2/km (comb)\n]
15735                               \nYes\n
10575                               \nYes\n
5542     [\nYes\n, \n118 g CO2/km (comb)\n]
11259    [\nYes\n, \n141 g CO2/km (comb)\n]
12833    [\nYes\n, \n156 g CO2/km (comb)\n]
10549    [\nYes\n, \n164 g CO2/km (comb)\n]
11126    [\nYes\n, \n104 g CO2/k