In [1]:
import pandas as pd
import numpy as np
from src import scout_car_clean as scc

%load_ext autoreload
%autoreload 2

In [2]:
import os
print(os.getcwd())

/media/oem/onetbsamdot/ezt/github/magnimind_hw


In [3]:
df_org = pd.read_json('./data/scout_car.json', lines=True)
df = df_org.copy()

In [4]:
"""
**Columns**
* url: url of autos
* short_description, description: Description of autos (in English and German) written by users
* make_model, make, model: Model of autos. Ex:Audi A1
* body_type, body: Body type of autos Example: van, sedans
* vat: VAT deductible, price negotiable
* registration, first_registration: First registration date and year of autos.
* prev_owner, previous_owners: Number of previous owners
* type: new or used
* next_inspection, inspection_new: information about inspection (inspection date,..)
* body_color, body_color_original: Color of auto Ex: Black, red
* paint_type: Paint type of auto Ex: Metallic, Uni/basic
* upholstery: Upholstery information (texture, color)
* gearing_type: Type of gear Ex: automatic, manual
* fuel : fuel type Ex: diesel, benzine
* co2_emission, emission_class, emission_label: emission information
* drive_chain: drive chain Ex: front,rear, 4WD
* consumption: consumption of auto in city, country and combination (lt/100 km)
* country_version
* entertainment_media
* safety_security
* comfort_convenience
* extras
* price: Price of cars
* km: km of autos
* hp: horsepower of autos (kW)
* displacement: displacement of autos (cc)
* warranty: warranty period (month)
* weight: weight of auto (kg)
* nr_of_doors: number of doors
* nr_of_seats : number of seats
* cylinders: number of cylinders
* gears: number of gears

"""

'\n**Columns**\n* url: url of autos\n* short_description, description: Description of autos (in English and German) written by users\n* make_model, make, model: Model of autos. Ex:Audi A1\n* body_type, body: Body type of autos Example: van, sedans\n* vat: VAT deductible, price negotiable\n* registration, first_registration: First registration date and year of autos.\n* prev_owner, previous_owners: Number of previous owners\n* type: new or used\n* next_inspection, inspection_new: information about inspection (inspection date,..)\n* body_color, body_color_original: Color of auto Ex: Black, red\n* paint_type: Paint type of auto Ex: Metallic, Uni/basic\n* upholstery: Upholstery information (texture, color)\n* gearing_type: Type of gear Ex: automatic, manual\n* fuel : fuel type Ex: diesel, benzine\n* co2_emission, emission_class, emission_label: emission information\n* drive_chain: drive chain Ex: front,rear, 4WD\n* consumption: consumption of auto in city, country and combination (lt/100 k

In [5]:
# Replace special characters and spaces in column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[\s\n]+', '_', regex=True)
    .str.replace(r'[^a-z0-9_]', '', regex=True)
    .str.replace(r'_+', '_', regex=True)
)

df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kw', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'nonsmoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'description',
       'emission_label', 'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [6]:
# df.drop(['entertainment_media', 'safety_security', 'comfort_convenience', 'extras'],axis=1,inplace=True)
# df.columns

In [7]:
len(np.unique(df['url']))

15919

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   url                            15919 non-null  object 
 1   make_model                     15919 non-null  object 
 2   short_description              15873 non-null  object 
 3   body_type                      15859 non-null  object 
 4   price                          15919 non-null  int64  
 5   vat                            11406 non-null  object 
 6   km                             15919 non-null  object 
 7   registration                   15919 non-null  object 
 8   prev_owner                     9091 non-null   object 
 9   kw                             0 non-null      float64
 10  hp                             15919 non-null  object 
 11  type                           15917 non-null  object 
 12  previous_owners                9279 non-null  

In [9]:
df.shape

(15919, 54)

In [10]:
# url unique count
len(np.unique(df['url']))

15919

In [11]:
# make_model unique count
len(np.unique(df['make_model']))

9

In [12]:
np.unique(df['make_model'], return_counts=True,equal_nan=True)

(array(['Audi A1', 'Audi A2', 'Audi A3', 'Opel Astra', 'Opel Corsa',
        'Opel Insignia', 'Renault Clio', 'Renault Duster',
        'Renault Espace'], dtype=object),
 array([2614,    1, 3097, 2526, 2219, 2598, 1839,   34,  991]))

In [13]:
# make separate columns for 'make' and 'model'
df['make_model'] = df['make_model'].str.lower().str.replace(' ', '_')
np.unique(df['make_model'], return_counts=True,equal_nan=True)

(array(['audi_a1', 'audi_a2', 'audi_a3', 'opel_astra', 'opel_corsa',
        'opel_insignia', 'renault_clio', 'renault_duster',
        'renault_espace'], dtype=object),
 array([2614,    1, 3097, 2526, 2219, 2598, 1839,   34,  991]))

In [14]:
# short description unique count, can be dropped
df['short_description'].fillna('none', inplace=True)
np.unique(df['short_description'], return_counts=True,equal_nan=True)

(array([' 1,6 CDTI**NAVI*Klimaaut*Tempomat*EURO6*TÜV NEU',
        ' 1.4 75 cv5 porte b-color', ' 1.4 TFSI Attraction (125 CV)', ...,
        'van 1.5 dci 75cv S&S E6', 'zoé life', 'Österr. Edition 16.CDTI'],
       dtype=object),
 array([ 1,  1,  6, ..., 24,  1,  1]))

In [15]:
df['short_description'].isnull().sum()

0

In [16]:
df['short_description'].fillna('none', inplace=True)
df['short_description'].isnull().sum()

0

In [17]:
# body type
df['body_type'].fillna('none', inplace=True)
df['body_type'] = df['body_type'].str.lower().str.replace('-', '_').str.replace(' ', '_')
np.unique(df['body_type'], return_counts=True,equal_nan=True)

(array(['compact', 'convertible', 'coupe', 'none', 'off_road', 'other',
        'sedans', 'station_wagon', 'transporter', 'van'], dtype=object),
 array([3153,    8,   25,   60,   56,  290, 7903, 3553,   88,  783]))

In [18]:
# price null check
df['price'].isnull().sum()

0

In [19]:
# vat
df['vat'].fillna('none', inplace=True) # not needed replace with np.nan
df['vat'] = df['vat'].str.lower().str.replace(' ', '_')
np.unique(df['vat'], return_counts=True,equal_nan=True)

(array(['none', 'price_negotiable', 'vat_deductible'], dtype=object),
 array([ 4513,   426, 10980]))

In [20]:
df['vat'].isnull().sum()

0

In [21]:
# km null check
df['km'].isnull().sum()

0

In [22]:
# registration null check:
df['registration'].isnull().sum()

0

In [23]:
np.unique(df['registration'], return_counts=True,equal_nan=True)

(array(['-/-', '01/2016', '01/2017', '01/2018', '01/2019', '02/2016',
        '02/2017', '02/2018', '02/2019', '03/2016', '03/2017', '03/2018',
        '03/2019', '04/2016', '04/2017', '04/2018', '04/2019', '05/2016',
        '05/2017', '05/2018', '05/2019', '06/2016', '06/2017', '06/2018',
        '06/2019', '07/2016', '07/2017', '07/2018', '07/2019', '08/2016',
        '08/2017', '08/2018', '08/2019', '09/2016', '09/2017', '09/2018',
        '09/2019', '10/2016', '10/2017', '10/2018', '11/2016', '11/2017',
        '11/2018', '11/2019', '12/2016', '12/2017', '12/2018', '12/2019'],
       dtype=object),
 array([1597,  376,  306,  511,  541,  472,  368,  539,  585,  536,  471,
         695,  543,  532,  380,  541,  506,  459,  404,  572,  440,  452,
         409,  532,  224,  176,  215,  396,    6,   94,  114,  285,    1,
         141,  149,  141,    5,  160,  154,   97,  142,  180,  110,    1,
         134,  123,  103,    1]))

In [24]:
# Split the 'registration' column into 'registration_month' and 'registration_year' use pd.to_datetime()
df[['registration_month', 'registration_year']] = df['registration'].str.split('/', expand=True)

# Replace invalid entries with 'none', convert to integer or float
df['registration_month'] = df['registration_month'].replace('-', 'none')
df['registration_year'] = df['registration_year'].replace('-', 'none')

# sample registration
df[['registration', 'registration_month', 'registration_year']].sample(25)

registration registration_month registration_year
2247       02/2019                 02              2019
15069      05/2017                 05              2017
10030      05/2019                 05              2019
1449       07/2018                 07              2018
12402          -/-               none              none
5455           -/-               none              none
14961      02/2016                 02              2016
2848       06/2016                 06              2016
13964      12/2017                 12              2017
14100      08/2017                 08              2017
4901       02/2018                 02              2018
12355      03/2018                 03              2018
605        07/2016                 07              2016
4980       05/2018                 05              2018
3784       04/2018                 04              2018
8650       12/2017                 12              2017
1556       07/2018                 07              2018
14478      09/2018                 09              2018
11806          -/-               none              none
3340           -/-               none              none
9105       02/2018                 02              2018
1326       10/2017                 10              2017
15515      02/2018                 02              2018
2715       04/2016                 04              2016
13890      07/2018                 07              2018

In [25]:
# prev_owner
df['prev_owner'].fillna('none',inplace=True)
np.unique(df['prev_owner'], return_counts=True, equal_nan=True)

(array(['1 previous owner', '2 previous owners', '3 previous owners',
        '4 previous owners', 'none'], dtype=object),
 array([8294,  778,   17,    2, 6828]))

In [26]:
df['prev_owner'] = df['prev_owner'].str.replace(' ', '_')
np.unique(df['prev_owner'], return_counts=True, equal_nan=True)

(array(['1_previous_owner', '2_previous_owners', '3_previous_owners',
        '4_previous_owners', 'none'], dtype=object),
 array([8294,  778,   17,    2, 6828]))

In [27]:
df[['prev_owner','previous_owners']].sample(25)

prev_owner previous_owners
12408              none             NaN
5119               none             NaN
2099               none             NaN
7232   1_previous_owner           \n1\n
4874   1_previous_owner           \n1\n
13215              none             NaN
13828              none             NaN
6826   1_previous_owner           \n1\n
3689   1_previous_owner           \n1\n
15547              none             NaN
14548              none             NaN
2341               none             NaN
1663               none             NaN
9561   1_previous_owner           \n1\n
2723   1_previous_owner           \n1\n
6432   1_previous_owner           \n1\n
1297   1_previous_owner           \n1\n
8507   1_previous_owner           \n1\n
6786   1_previous_owner           \n1\n
4388   1_previous_owner           \n1\n
9177               none             NaN
9803   1_previous_owner           \n1\n
11790  1_previous_owner           \n1\n
994    1_previous_owner           \n1\n
5237               none             NaN

In [28]:
# next inspection
df['next_inspection'].fillna('none',inplace=True)
df[df['next_inspection'] != 'none']['next_inspection'].sample(25)

7225                  [\n05/2021\n, \nEuro 6\n]
15364    [\n04/2020\n, \n116 g CO2/km (comb)\n]
4943     [\n07/2021\n, \n111 g CO2/km (comb)\n]
1178     [\n11/2020\n, \n102 g CO2/km (comb)\n]
4086     [\n05/2020\n, \n104 g CO2/km (comb)\n]
7278     [\n06/2021\n, \n133 g CO2/km (comb)\n]
14425                               \n11/2021\n
12388    [\n01/2021\n, \n133 g CO2/km (comb)\n]
11942    [\n06/2021\n, \n141 g CO2/km (comb)\n]
1522     [\n07/2021\n, \n102 g CO2/km (comb)\n]
5820     [\n05/2021\n, \n152 g CO2/km (comb)\n]
6705     [\n02/2021\n, \n127 g CO2/km (comb)\n]
11598    [\n12/2020\n, \n133 g CO2/km (comb)\n]
2102                                \n03/2022\n
1435      [\n05/2020\n, \n98 g CO2/km (comb)\n]
14890              [\n02/2022\n, \n4 (Green)\n]
14483    [\n07/2021\n, \n133 g CO2/km (comb)\n]
11226                               \n05/2021\n
14657     [\n03/2021\n, \n90 g CO2/km (comb)\n]
6442                                \n07/2019\n
7420      [\n06/2021\n, \n93 g CO2/km (c

In [29]:
df['next_inspection'].str[0].str.replace('\n','').value_counts() # get date and using pd.to_datetime()

next_inspection
n          12384
             710
06/2021      437
03/2021      172
05/2021      153
           ...  
12/2017        1
01/2023        1
01/1921        1
11/2022        1
03/2017        1
Name: count, Length: 70, dtype: int64

In [30]:
df['next_inspection'] = df['next_inspection'].str[0].str.replace('\n','')
df['next_inspection'] = df['next_inspection'].str[0].str.replace('n','')
df['next_inspection'] = df['next_inspection'].fillna(np.nan)
pd.to_datetime(df['next_inspection'].str[0].str.replace('\n',''))

/tmp/ipykernel_37214/3645520942.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df['next_inspection'].str[0].str.replace('\n',''))


DateParseError: day is out of range for month: 0, at position 0

In [ ]:
df['next_inspection'].unique()

In [ ]:
df['inspection_new'].fillna('none',inplace=True)
df[df['inspection_new'] != 'none']['inspection_new'].sample(25)

In [ ]:
# hp
np.unique(df['hp'], return_counts=True, equal_nan=True)

In [ ]:
df['kw'] = df['hp'].str.extract('(\d+)').copy()
df['kw'] = df['kw'].fillna('none').copy()
df['kw'].sample(4)

In [ ]:
df['kw'].sample(4)

In [ ]:
df[['kw','hp']].sample(50)

In [ ]:
!python3 scout_car_clean.py